name: omi-command-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - nextflow >=23.10.0
  - singularity
  - apptainer
  - curl
  - wget
  - numpy
  - pandas
  - fastapi>=0.115.0
  - uvicorn>=0.25.0
  - python-jose>=3.3.0
  - python-multipart>=0.0.6
